# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: frontend build Use Node.js ${{ matrix.node-version }}
      working-directory: ./frontend
      run: |
        npm i
        npm run deploy --if-present
 
    - name: api-server build
      working-directory: ./backend
      run: |
        npm i
        npm run build
