# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2 
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: create frontend env file
        run: |
          cd frontend
          touch .env.production
          echo REACT_APP_KAKAO_REST_API_KEY = ${{secrets.REACT_APP_KAKAO_REST_API_KEY}}  >> .env
          cat .env.production

      - name: frontend install dependencies & build
        run: |
          cd frontend
          npm install
          npm run build

      - name: move build file to backend
        run: |
          cd frontend
          rm -rf ../backend/build
          mv build ../backend

      - name: create backend end file
      - run: |
          cd backend
          touch .env
          echo DATABASE_URL = ${{secrets.DATABASE_URL }} >> .env
          echo DB_HOST = ${{ secrets.DB_HOST }} >> .env
          echo DB_USER = ${{ secrets.DB_USER }} >> .env
          echo DB_NAME = ${{ secrets.DB_NAME }} >> .env
          echo DB_PASS = ${{ secrets.DB_PASS }} >> .env
          cat .env

      - name: backend install dependencies & build
        run: |
          cd backend
          npm install
          npm run prisma:generate
          npm run build
      
      - name: Restart Pm2
        run: |
          pm2 restart withbook
