# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        
      - name: add frontend env
      - run: | 
          cd frontend
          touch .env
          echo KAKAO_REST_API_KEY = ${{secrets.KAKAO_REST_API_KEY}}  >> .env
          cat .env
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd frontend
          npm install
          npm run deploy
      - run: |
          cd backend
          npm install
          npm run build
      
      - name: Create env file
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASS }}
        
        run: |
          cd backend
          touch .env
          echo DB_HOST = $DB_HOST >> .env
          echo DB_USER = $DB_USER >> .env
          echo DB_NAME = ${{ secrets.DB_NAME }} >> .env
          echo DB_PASS = ${{ secrets.DB_PASS }} >> .env
          cat .env
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')
 
